# Generated by Django 5.1.1 on 2026-04-15 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Логин может содержать только буквы, цифры и символы @/./+/-/_', regex='^[\\w.@+-]+\\z')], verbose_name='Логин'),
        ),
    ]
